name: 'Release: Build & Package App'

on:
  release:
    types: [created]

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            builds-args: '--bundles nsis'
            target: ''
            asset-prefix: '01'
          - platform: 'macos-latest'
            target: aarch64-apple-darwin
            asset-prefix: '02'
          - platform: 'macos-latest'
            target: x86_64-apple-darwin
            asset-prefix: '02'
          - platform: 'ubuntu-22.04'
            target: ''
            asset-prefix: '03'
          - platform: 'ubuntu-22.04-arm'
            target: ''
            asset-prefix: '03'
          - platform: 'ubuntu-24.04'
            target: ''
            asset-prefix: '03'
          - platform: 'ubuntu-24.04-arm'
            target: ''
            asset-prefix: '03'
    uses: ./.github/workflows/build.yml
    with:
      release-id: ${{ github.event.release.id }}
      platform: ${{ matrix.platform }}
      target: ${{ matrix.target }}
      build-args: ${{ matrix.args }}
      asset-name-pattern: "[name]_v[version]_[platform]_[arch][ext]"
      asset-prefix: ${{ matrix.asset-prefix }}
    secrets: inherit
    permissions:
      contents: write
